### ISSUE TITLE
Consider populating git origin

### ISSUE THREAD

**Issue by jonathantneal** [postcss/postcss-plugin-boilerplate#10]
Since the boilerplate leverages GitHub, we might consider saving developers the trouble of adding the origin:

```sh
git remote add origin git@github.com:GITHUB_NAME/PLUGIN_NAME.git
```

**Comment by ai** [comment]
Yeap, it looks like carefully.

But I afraid that it is not really copy-paste command. And GitHub anyway suggest better CLI command, when you will create a repository.
