### ISSUE TITLE
Can't clone repository

### ISSUE THREAD

**Issue by moshemo** [postcss/postcss-plugin-boilerplate#27]
When I enter the following in the command line:

    git clone https://github.com/postcss/postcss-plugin-boilerplate.git

This is the message that I get:

    Cloning into 'postcss-plugin-boilerplate'...
    fatal: unable to access 'https://github.com/postcss/postcss-plugin-boilerplate.git/': error setting certificate verify locations:
      CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
      CApath: none

Any idea why this isn't working?   In case it is relevant -- I am on a Windows 10 machine.

**Comment by ai** [comment]
Seems like you have HTTPS issue. I think it is a git and Windows issue.

BTW, I think developing on Windows is not a good idea. Only 43% of developers uses Windows with node.js. And most of opensource top developers uses UNIX.

Try Ubuntu.

**Comment by moshemo** [comment]
Thanks for the response and I'll take a look into Ubuntu (in particular, a dual boot solution).

Just out of curiosity, though - what percentage of users use Linux and what percentage Mac?  After all, 43% is actual a pretty decent stat in a three-way race.  It means that Linux and Mac have to share between the two of them the other 57%.
