### ISSUE TITLE
loudRejection/api is deprecated warning when running tests

### ISSUE THREAD

**Issue by alexlibby** [postcss/postcss-plugin-boilerplate#34]
Hi,
I've been creating a new plugin - as part of running the tests, I'm getting this error:

> C:\wamp\www\postcss\node_modules\postcss-filter-tint>npm test
> postcss-filter-tint@0.0.0 test C:\wamp\www\postcss\node_modules\postcss-filter-tint
> ava && eslint *.js
loudRejection/api is deprecated. Use the currently-unhandled module instead.
   1 passed

Some digging has unearthed a known issue within AVA, which requires an update to 0.15.2. I've checked the package.json file, which indicates version 0.14.0 is installed, which was updated in issue 33. I've done a manual update to 0.15.2 for AVA, then removed this line from the package.json file within the plugin folder:

```"ava": "^0.14.0",```

...and reinstalled using ```npm install ava --save-dev```, within the plugin folder (it was installed globally beforehand, but I am not sure if this was enough). This does appear to have fixed the issue though - you may want to look at updating your package.json file at some point:

> C:\wamp\www\postcss\node_modules\postcss-filter-tint>npm test
> postcss-filter-tint@0.0.0 test C:\wamp\www\postcss\node_modules\postcss-filter-tint
> ava && eslint *.js
   1 passed
C:\wamp\www\postcss\node_modules\postcss-filter-tint>

Hope this helps anyone who comes across the same issue!

**Comment by ai** [comment]
Fixed. Thanks b35626b
