### ISSUE TITLE
Can't pass eslint test on node 0.12

### ISSUE THREAD

**Issue by Pustur** [postcss/postcss-plugin-boilerplate#36]
Hello, i recently made my first plugin for PostCSS using this boilerplate (thanks for making it!)

However, i'm having an issue:

According to the [guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#21-plugin-must-be-tested) i have to test the plugin on node 0.12.

But the [error i'm getting](https://travis-ci.org/Pustur/postcss-italian-stylesheets/jobs/157715971) comes from eslint. How do i proceed?

Also, if anyone has feedback on [the project](https://github.com/Pustur/postcss-italian-stylesheets) i'd really like to hear it.  
I'm new to PostCSS / Testing / publishing NPM packages so if i'm doing anything incorrectly let me know.

```
  1164 tests passed [19:36:08]
/home/travis/build/Pustur/postcss-italian-stylesheets/node_modules/eslint/lib/cli.js:18
const fs = require("fs"),
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/Pustur/postcss-italian-stylesheets/node_modules/eslint/bin/eslint.js:29:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
Done. Your build exited with 1.
```

**Comment by TrySound** [comment]
You can use this trick and prevent linting on 0.12
https://github.com/TrySound/postcss-inline-svg/blob/master/package.json#L44-L45
https://github.com/TrySound/postcss-inline-svg/blob/master/.travis.yml#L5

**Comment by ai** [comment]
@Pustur thanks for report, I forgot about it.

@TrySound good workaround!

**Comment by Pustur** [comment]
Thanks a lot for the quick responses!  
I used @TrySound workaround and, well, it worked. 😄

**Comment by ai** [comment]
I thought and decide that will be better to remove node.js 0.12. If ESLint doesn’t support — it is good marker, that we don’t need it.

If plugin developers care about node.js 0.12 she/he always could add it again.
