### ISSUE TITLE
Option to skip installation

### ISSUE THREAD

**Issue by princed** [postcss/postcss-plugin-boilerplate#38]
To be able to use yarn instead of npm.

**Comment by ai** [comment]
What UI do you suggest?

**Comment by princed** [comment]
Just ask: "Install dependencies after configuration?" in the end.
`Yes` should probably be default answer.

**Comment by ai** [comment]
This question will not be useful for 90% of users. Not a good UX. Maybe we can detect, that yarn is installed and ask to use it if we found it.

**Comment by princed** [comment]
I think it's a good idea in general to let people know that script is going to install something as a last step.

Imagine that there is no network available: installation fails and you don't even know if everything was properly configured and is fully functional.

**Comment by ai** [comment]
Hm. Good point. Do you want to send PR?

**Comment by princed** [comment]
I'm not sure if I have enough time in nearest future.

**Comment by ai** [comment]
Done https://github.com/postcss/postcss-plugin-boilerplate/commit/7b46289cf54bfea0bbc3d4f3460402cc070b20ac

**Comment by princed** [comment]
Hmm, I thought, you agreed with my arguments about skipping installation at all.

**Comment by ai** [comment]
I agreed with your arguments about `yarn` :D

**Comment by ai** [comment]
OK, I will add `--no-install` option :).

**Comment by ai** [comment]
Done 159bf9c
