### ISSUE TITLE
Don't remove postcss-plugin-boilerplate folder after usage

### ISSUE THREAD

**Issue by princed** [postcss/postcss-plugin-boilerplate#4]
E.g. use copy and replace strategy instead of current replace and move.
So we don't have to clone repo again for later usage.

I'd make a PR if you're agree.

**Comment by ai** [comment]
I understand you, but there is a two cases:

1. I think most of users will create only one plugin pre month (most of them will create only one plugin at all).
2. Very important to use latest version of boilerplate.

**Comment by ai** [comment]
But we can add a option to script to prevent directory remove. But in this case we should change `start` logic, because right now it change code in current dir and then rename it. New version of `start` should copy directory and change file there.

**Comment by ai** [comment]
Done eac614d

**Comment by princed** [comment]
:+1:
