### ISSUE TITLE
Add jest coverage reports

### ISSUE THREAD

**Issue by atk** [postcss/postcss-plugin-boilerplate#41]
Or is there a reason not to? Just add

```
  "jest": {
    "collectCoverage": true
  }
```

to the package.json and have beautiful reports of which lines of your plugins are untested.

**Comment by ai** [comment]
I am not sure that report will help as is.

In my project I just add minimum coverage rate. But it is very depends on project.

So I think it will be better to keep it up to developers.

**Comment by ai** [comment]
But I like coverage too :). Try to keep 100% in my projects :D.

**Comment by atk** [comment]
Maybe you can add a configuration switch?

**Comment by ai** [comment]
Just add it manually if you like coverage
