### ISSUE TITLE
`run` function does not make tests fail on error

### ISSUE THREAD

**Issue by matthias-t** [postcss/postcss-plugin-boilerplate#48]
When using the provided `run` function to test the plugin, if the input makes the plugin error, the test doesn't fail in Jest. It will print this:
```
(node:15848) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Example Error
(node:15848) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
but the test will pass.

**Comment by ai** [comment]
Do you wrote `return` before `run`?

```js
it("test name", () => {
  return run(…)
})
```

**Comment by matthias-t** [comment]
@ai thanks, that fixed it. Does that mean you can only have one `run()` in each `it()` test case?

**Comment by ai** [comment]
You can wrap several `run` in `Promise.all`.

```
  return Promise.all([
    run(),
    run(),
    run()
  ])
```

`run` returns simple Promise.

**Comment by matthias-t** [comment]
@ai That's perfect. Thanks a lot for your time!
