### ISSUE TITLE
package.json seems to currently be invalid, and you can't run start

### ISSUE THREAD

**Issue by rpearce** [postcss/postcss-plugin-boilerplate#52]
The word `KEYWORDS` seems to be creating a JSON parsing issue. I'm not sure what was intended here, or I'd make a PR:
https://github.com/postcss/postcss-plugin-boilerplate/blob/master/package.json#L8

**Comment by ai** [comment]
It was indented `node ./postcss-plugin-boilerplate/start` will replace `KEYWORDS`.

What command do you call and what error message do you have?

**Comment by rpearce** [comment]
```
~/projects
λ git clone https://github.com/postcss/postcss-plugin-boilerplate.git
Cloning into 'postcss-plugin-boilerplate'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 431 (delta 13), reused 24 (delta 9), pack-reused 399
Receiving objects: 100% (431/431), 63.23 KiB | 594.00 KiB/s, done.
Resolving deltas: 100% (227/227), done.

~/projects
λ node ./postcss-plugin-boilerplate/start
internal/modules/cjs/loader.js:272
    throw e;
    ^

SyntaxError: Error parsing /Users/rpearce/projects/postcss-plugin-boilerplate/package.json: Unexpected token K in JSON at position 158
    at parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:260:20)
    at readPackageScope (internal/modules/cjs/loader.js:285:19)
    at shouldUseESMLoader (internal/modules/run_main.js:36:15)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:66:24)
    at internal/main/run_main_module.js:17:47 {
  path: '/Users/rpearce/projects/postcss-plugin-boilerplate/package.json'
}
```
Removing that KEYWORDS bit lets the CLI work, but I assume that's not what you want...

**Comment by rpearce** [comment]
```
λ node --version
v13.13.0
```

**Comment by ai** [comment]
Seems like Node changed behaviour and now we need a different template language. Thanks for the report.

I will fix it later, when I will update boilerplate to PostCSS 8.

**Comment by Tofandel** [comment]
Same issue here, the solution is to rename the package.json file to something like package.json.tpl and have the script rename it
For some reason node tries to read the package.json in the directory you try to run a script

**Comment by ai** [comment]
@Tofandel yeap, let’s rename it to `.tpl`. Send PR.

**Comment by ai** [comment]
Thanks @Tofandel
