### ISSUE TITLE
Change to template repository?

### ISSUE THREAD

**Issue by Semigradsky** [postcss/postcss-plugin-boilerplate#56]
It is just a suggestion.

Github has feature - [template repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)

[Users can create own plugins by using this template](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template). All these repos will have link to template like this:
![image](https://user-images.githubusercontent.com/1198848/92880524-c59bc780-f416-11ea-9c78-96f08a9982d2.png)
Git history will have one commit "Initial commit".

Example: https://github.com/google/eleventy-high-performance-blog

**Comment by ai** [comment]
Can we have a variables in template? Like user enter plugin name and we put it in all places automatically?

**Comment by Semigradsky** [comment]
Not yet - https://github.com/isaacs/github/issues/1716

**Comment by ai** [comment]
In this case it will decrease DX. Popular told often is not the best one.
