### ISSUE TITLE
Any way to make my plugin not require Postcss 8?

### ISSUE THREAD

**Issue by gVguy** [postcss/postcss-plugin-boilerplate#61]
Hi!

I made [this plugin](https://github.com/gVguy/postcss-vwh), (thanks for this awesome boilerplate btw! ✨) and I'm trying to use it in my vue-cli project, but I'm getting this error:
`Syntax Error: Error: PostCSS plugin postcss-vwh requires PostCSS 8.`

As I understand the error can be fixed by upgrading to a newer postcss-loader version, but unfortunately vue-cli runs on Webpack 4, so I have to use the one I have – 4.2.0

Is there a way to make my plugin less demanding, so I (and other people using Webpack 4) could make use of it?
eg, postcss-color-function, which only requires postcss version 6.0.23, works

Thanks

**Comment by ai** [comment]
Short answer: no.

Long answer: you can create an ugly adapter to convert PostCSS 8 plugins to PostCSS 7. You can look for this adapter in Tailwind CSS. But at the end, you will spend more time supporting this adapter.

It is much better for you as maintainer to ask user to update to PostCSS 8.
