### ISSUE TITLE
Consider converting to template project

### ISSUE THREAD

**Issue by ALMaclaine** [postcss/postcss-plugin-boilerplate#62]
Please consider converting this to a template project:

https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by ai** [comment]
Why we should move to GitHub template in this case?

**Comment by lumburr** [comment]
I don't agree with him.
But I think that create new project to development plugin would be nice to integrate into `postcss-cli`.

**Comment by ai** [comment]
I am closing this issue because we need smarter system with templates and variables
