### ISSUE TITLE
Support for TypeScript

### ISSUE THREAD

**Issue by emme1444** [postcss/postcss-plugin-boilerplate#65]
Consider adding a `--ts, --typescript` flag for use with TypeScript instead of JavaScript.

Like generating a `tsconfig.json` and adding the `typescript` devDependency, along with scripts for building and cleaning as well as the types necessary, if any.

**Comment by ai** [comment]
It is better to create another boilerplate for TS plugins.

I personally against build tools in open source libraries (like PostCSS plugins) since they reduce maintability a lot (I personally prefer TS in big applications, not in libraries).

But you may have another option.
