### ISSUE TITLE
workflows failing with dependencies installation

### ISSUE THREAD

**Issue by RiadhAdrani** [postcss/postcss-plugin-boilerplate#70]
Hello,

I am creating a new plugin that allow the user to skip a file with a top comment;

```css
/* @ignore */

.will-be-ignore {}
```

The problem is, when I push to my [repo](https://github.com/RiadhAdrani/postcss-plugin-ignore-file), github actions dependencies installation fails due to [node version mismatching](https://github.com/RiadhAdrani/postcss-plugin-ignore-file/actions/runs/5865985234/job/15903950185)

I am doing something wrong ?

Thanks.

**Comment by ai** [comment]
The problem is because you are using Node.js 15 which has no security updates anymore.

Never use odd versions. They are development previews and not production version.

Use Node.js 20.

**Comment by RiadhAdrani** [comment]
@ai yep I know, but shouldn't the template be updated ?

**Comment by ai** [comment]
Sure, in the process

**Comment by ai** [comment]
The fix was released at 2.0.
